name: Spain Lab
highlighter: pygments
permalink: /:year/:month/:day/:title.html
#markdown: rdiscount
markdown: redcarpet
redcarpet:
  extensions: [
		"no_intra_emphasis",
		"fenced_code_blocks",
		"autolink",
		"strikethrough",
		#"superscript"
		]


scholar:
  style: _plugins/american-chemical-society.csl
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: page

  details_dir:    publications
  details_layout: bibtex.html
  details_link:   Details
