name: Seb Spain Beta Site
pygments: true
permalink: /:categories/:title.html
#markdown: rdiscount
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
